name       : keybinder
version    : 0.3.0
release    : 1
source     :
    - https://github.com/engla/keybinder/archive/v0.3.0.tar.gz : 8e8d77386b9e29556fab097c31aec643d36a33d201733b7b999179abcba7774e
license    : GPL-2.0
summary    : Keybinder for GTK-based applications
description: |
    keybinder is a library for registering global key bindings, for gtk-based applications. Python bindings included.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(pygobject-2.0)
    - gnome-common
    - gtk-doc
setup      : |
    ./autogen.sh --prefix=/usr
    %configure
build      : |
    %make
install    : |
    %make_install
    ln -s /usr/lib64/pkgconfig/keybinder.pc %installroot%/usr/lib64/pkgconfig/keybinder-3.0.pc
