name       : keybinder
version    : 0.3.1
release    : 3
source     :
    - https://github.com/kupferlauncher/keybinder/releases/download/v0.3.1/keybinder-0.3.1.tar.gz : 879f07130ac64792ddb9fd758e6673119283bda37d75573787ae22af8684a240
license    : GPL-2.0
component  : desktop.library
summary    : Keybinder for GTK-based applications
description: |
    keybinder is a library for registering global key bindings, for gtk-based applications. Python bindings included.
builddeps  :
    - pkgconfig(pygtk-2.0)
    - gnome-common
    - gtk-doc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
