name       : keybinder
version    : 0.3.2
release    : 2
source     :
    - https://github.com/kupferlauncher/keybinder/archive/keybinder-3.0-v0.3.2.tar.gz : 2eec50be6dfafa672d719e719f639df10403f270b2473e60deb2fb8455d13c51
license    : GPL-2.0
component  : desktop.library
summary    : Keybinder for GTK-based applications
description: |
    keybinder is a library for registering global key bindings, for gtk-based applications. Python bindings included.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gobject-introspection-1.0)
    - gnome-common
    - gtk-doc
setup      : |
    %autogen
    %configure
build      : |
    %make
install    : |
    %make_install
