name       : keybinder
version    : 0.3.2
release    : 13
source     :
    - https://github.com/kupferlauncher/keybinder/releases/download/v0.3.1/keybinder-0.3.1.tar.gz : 879f07130ac64792ddb9fd758e6673119283bda37d75573787ae22af8684a240
    - https://github.com/kupferlauncher/keybinder/releases/download/keybinder-3.0-v0.3.2/keybinder-3.0-0.3.2.tar.gz : e6e3de4e1f3b201814a956ab8f16dfc8a262db1937ff1eee4d855365398c6020
license    : GPL-2.0-or-laster
extract    : no
component  : desktop.library
summary    : Keybinder for GTK-based applications
description: |
    keybinder is a library for registering global key bindings, for gtk-based applications. Python bindings included.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygtk-2.0)
    - gnome-common
    - gtk-doc
setup      : |
    mkdir keybinder-legacy keybinder-3.0
    tar --strip-components=1 -xf $sources/keybinder-0.3.1.tar.gz -C keybinder-legacy
    tar --strip-components=1 -xf $sources/keybinder-3.0-$version.tar.gz -C keybinder-3.0
    for i in keybinder-legacy keybinder-3.0; do
        pushd $i
        %configure
        popd
    done
build      : |
    cd $workdir
    ls
    for i in keybinder-legacy keybinder-3.0; do
        pushd $i
        %make
        popd
    done
install    : |
    cd $workdir
    for i in keybinder-legacy keybinder-3.0; do
        pushd $i
        %make_install
        popd
    done
